
services: 
  recognize:
    image: postgres:15.3
    container_name: recognize_DB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=recognizeDB
    volumes:
      - ./postgres:/var/lib/postgresql/data